name: Build Linux ARM64

on:
  push:
    paths:
      - "**/*.c"
      - ".github/workflows/build-linux-arm64.yml"
  workflow_dispatch:

jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ARM64 compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        run: |
          aarch64-linux-gnu-gcc -pthread -O2 -Wall -Wextra \
            cfnat_linux_ipmode.c \
            -o cfnat_linux_arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfnat_linux_arm64
          path: cfnat_linux_arm64
